[package]
name = "jector"
version = "0.1.0"
authors = ["lewis <me@lewis.to>"]
edition = "2018"

[lib]
name = "jector"

[[bin]]
name = "jector"
doc = false

[dependencies]
winapi = { version = "0.3.9", features = ["winnt", "winuser", "processthreadsapi", "handleapi", "memoryapi", "winbase", "errhandlingapi", "synchapi", "tlhelp32", "psapi", "wow64apiset", "impl-default", "sysinfoapi"] }
pelite = "0.9.0"
bitflags = "1.2.1"
field-offset = "0.3.2"
dynasm = "1.0.0"
dynasmrt = "1.0.0"
patternscan = "0.1.1"
rand = "0.7.3"
clap = "2.33.3"
anyhow = "1.0.37"
thiserror = "1.0.23"
